import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import BbBackgroundVideo from '@/components/atoms/BbBackgroundVideo'
import BbModal, { BbModalContent, BbModalFooter, BbModalHeader } from '@/components/atoms/BbModal'

const Home: NextPage = () => {
  const [showModal, setShowModal] = useState<boolean>(false)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <BbBackgroundVideo src='/videos/top_firstview.mp4' />
      <button onClick={() => setShowModal(true)}>Open</button>
      <BbModal showModal={showModal} setShowModal={setShowModal}>
        <BbModalHeader>ここがタイトル</BbModalHeader>
        <BbModalContent>ここがコンテンツ</BbModalContent>
        <BbModalFooter>ここがフッター</BbModalFooter>
      </BbModal>
      <div className='mt-96'>aaaa</div>
      <div className='mt-96'>aaaa</div>
      <div className='mt-96'>aaaa</div>
      <div className='mt-96'>aaaa</div>
    </>
  )
}

export default Home
