import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-96">aaaa</div>
      <div className="mt-96">aaaa</div>
      <div className="mt-96">aaaa</div>
      <div className="mt-96">aaaa</div>
    </>
  );
};

export default Home;
